In [4]:
import numpy as np


O D tensors


In [5]:

arr = np.array(5)

print(arr)
print(arr.ndim)
print(arr.shape)


5
0
()


1-D vector


In [7]:
a = np.array([1,2,3])

print(a)
print(a.ndim)
print(a.shape)


[1 2 3]
1
(3,)


2-D Matrix


In [12]:


a = np.array([
    [1, 2],
    [3, 4]
])

print(a)
print(a.ndim)
print(a.shape)

[[1 2]
 [3 4]]
2
(2, 2)


3-D Tensor

In [13]:
a = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [4,5],
        [23,45]
    ]
])

print(a)
print(a.ndim)
print(a.shape)


[[[ 1  2]
  [ 3  4]]

 [[ 4  5]
  [23 45]]]
3
(2, 2, 2)
